# Generated by Django 2.0.6 on 2018-06-05 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='App name', max_length=50)),
                ('description', models.TextField(default='App description')),
                ('app_link', models.CharField(default='http://', max_length=50)),
                ('app_icon', models.ImageField(default='default_icon.png', upload_to='image/')),
                ('screen_shot', models.ImageField(default='default_screen_shot.png', upload_to='image/')),
                ('votes', models.IntegerField(default=1)),
                ('publish_date', models.DateField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
